apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: PATH_peace1
        value: "true"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH_peace2
        value: "true"
        rate_limit:
          unit: minute
          requests_per_unit: 3